
service: hello-world
frameworkVersion: '2'
    
provider:
  name: aws
  runtime: python3.6

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: false

package:
  individually: false
  exclude:
    - '**/*'
  include:
    - handler.py

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post